#!/bin/sh
set -e

TEMPLATE_PATH="/app/dist/runtime-config.template.js"
OUTPUT_PATH="/app/dist/runtime-config.js"

API_BASE_RUNTIME="${ADMIN_BACKEND_BASE_URL:-${VITE_API_URL:-}}"
MUCAJEY_BASE_RUNTIME="${ADMIN_FRONTEND_MUCAJEY_API_URL:-${VITE_MUCAJEY_API_URL:-}}"
MUCAJEY_API_KEY_RUNTIME="${ADMIN_FRONTEND_MUCAJEY_API_KEY:-${VITE_MUCAJEY_API_KEY:-}}"

if [ -f "$TEMPLATE_PATH" ]; then
  export RUNTIME_API_BASE_URL="$API_BASE_RUNTIME" \
         RUNTIME_MUCAJEY_API_URL="$MUCAJEY_BASE_RUNTIME" \
         RUNTIME_MUCAJEY_API_KEY="$MUCAJEY_API_KEY_RUNTIME"

  envsubst '${RUNTIME_API_BASE_URL} ${RUNTIME_MUCAJEY_API_URL} ${RUNTIME_MUCAJEY_API_KEY}' < "$TEMPLATE_PATH" > "$OUTPUT_PATH"
fi

if [ ! -s "$OUTPUT_PATH" ]; then
  echo 'window.__APP_CONFIG__ = {};' > "$OUTPUT_PATH"
fi

exec "$@"
